
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async checkIsStateReady() : Promise<boolean> {
    return await TAURI_INVOKE("check_is_state_ready");
},
async getConfig() : Promise<Result<AppConfig, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConfig(config: AppConfig) : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSpace(name: string, description: string, llmConfig: LLMConfig, embeddingConfig: EmbeddingConfig) : Promise<Result<number, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_space", { name, description, llmConfig, embeddingConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSpace(spaceId: number, name: string, description: string, llmConfig: LLMConfig, embeddingConfig: EmbeddingConfig) : Promise<Result<boolean, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_space", { spaceId, name, description, llmConfig, embeddingConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSpaceById(spaceId: number) : Promise<Result<Space, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_space_by_id", { spaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllSpaces() : Promise<Result<Space[], null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_spaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addRoot(spaceId: number, path: string) : Promise<Result<number, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_root", { spaceId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRootsBySpaceId(spaceId: number) : Promise<Result<IndexedRoot[], null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_roots_by_space_id", { spaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFilesByIds(ids: number[]) : Promise<Result<FileMetadata[], null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_files_by_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async indexSpace(spaceId: number) : Promise<Result<boolean, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_space", { spaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async processSpace(spaceId: number) : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_space", { spaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchByEmdedding(spaceId: number, query: string, limit: number) : Promise<Result<VectorSearchResult[], null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_by_emdedding", { spaceId, query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
backendReadyEvent: BackendReadyEvent,
errorEvent: ErrorEvent,
statusEvent: StatusEvent
}>({
backendReadyEvent: "backend-ready-event",
errorEvent: "error-event",
statusEvent: "status-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AIPrompt = { system_prompt: string; user_prompt: string }
export type AppConfig = { theme?: string; indexer_parallelism?: number; default_openai_url: string | null }
export type BackendReadyEvent = null
export type EmbeddingConfig = { api_base_url: string; api_key: string; model: string; dimensions: number }
export type ErrorEvent = { message: string; context: string | null }
export type FileMetadata = { id: number; root_id: number; absolute_path: string; filename: string; file_extension: string; file_size: number; description: string | null; modified_at_fs: string; last_indexed_at: string | null; content_hash: string | null; indexing_status: string; indexing_error_message: string | null }
export type IndexedRoot = { id: number; space_id: number; path: string; status: string }
export type LLMConfig = { api_base_url: string; api_key: string; model: string; text_processing_prompt: AIPrompt; image_processing_prompt: AIPrompt; default_processing_prompt: AIPrompt }
export type Space = { id: number; name: string; description: string | null; embedding_config: EmbeddingConfig; llm_config: LLMConfig; created_at: string }
export type StatusEvent = { status: StatusType; message: string | null; total: number | null; processed: number | null }
export type StatusType = "Idle" | "Indexing" | "Processing" | "Notification" | "Error"
export type VectorSearchResult = { chunk_id: number; content: string; file_id: number; absolute_path: string; filename: string; distance: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
